# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD affected modules

on:
  pull_request:
    branches: ['master']

jobs:
  pull-request:
    name: Running on node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['18.x']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests on affected modules
        run: npx nx affected --target=test --base=origin/master --parallel

      - name: Run unit build on affected modules
        run: npx nx affected --target=build --base=origin/master --parallel
